---

  - name: Update apt-get
    apt: update_cache=yes

  - name: Upgrade base packages
    apt: upgrade=yes

  - name: Install required and useful utilities
    apt: name={{ item }} state=latest
    with_items:
    - ansible
    - lynx
    - git

  - name: MongoDB | Fetch 10Gen signing key
    command: apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10

  - name: MongoDB | Add 10Gen repository
    shell: 
      echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/10gen.list
      creates=/etc/apt/sources.list.d/10gen.list

  - name: MongoDB | Install latest MongoDB release 
    apt: pkg=mongodb-10gen state=present update_cache=yes

  # Ensure service is running.
  - name: MongoDB | Insure deamon is running correctly
    service: name=mongodb state=started

  - name: Install core python utilities
    apt: name={{ item }} state=latest
    with_items:
    - python-pip
    - python-dev
    - build-essential
    - libmysqlclient-dev