---

  - name: System | Update apt-get
    apt: update_cache=yes

  - name: System | Upgrade base packages
    apt: upgrade=yes

  - name: System | Install useful utilities
    apt: name={{ item }} state=latest
    with_items:
    - software-properties-common
    - lynx
    - git
    - vim
    - memcached
    - python-software-properties
    - python-lxml

  - name: System | Set hostname
    lineinfile: 
      dest=/etc/hosts
      state=present
      line="127.0.0.1     {{ ansible_hostname }}"

  #Later add ansible

  - name: Memcached | Ensure deamon is running correctly
    service: name=memcached state=started

  - name: MongoDB | Fetch 10Gen signing key
    command: apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10

  - name: MongoDB | Add 10Gen repository
    shell: 
      echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/10gen.list
      creates=/etc/apt/sources.list.d/10gen.list

  #- name: MongoDB | Install latest MongoDB release 
  #  apt: pkg=mongodb-10gen state=present update_cache=yes

  - name: MongoDB | Install latest MongoDB release
    apt: pkg=mongodb-org state=present update_cache=yes

  - name: MongoDB | Ensure deamon is running correctly
    service: name=mongodb state=started

  - name: Python | Install core python utilities
    apt: name={{ item }} state=latest
    with_items:
    - python-pip
    - python-dev
    - build-essential
    - libmysqlclient-dev

  - name: PIP | Upgrade
    pip: name=pip extra_args='--upgrade'

  - name: PIP | Install Standard Libraries
    pip: name={{ item }} state=present
    with_items:
    - Django
    - pymongo
    - geoip2
    - supervisor
    - uwsgi

  - name: NGINX | Install nginx
    apt: name=nginx

  - name: NGINX | Ensure deamon is running correctly
    service: name=nginx state=started

  - name: NGINX | Ensure boot on start
    command: update-rc.d nginx defaults

  - name: MySQL | Install MySQL
    action: apt pkg={{ item }} state=installed
    tags: common
    with_items:
      - mysql-server
      - mysql-client
      - python-mysqldb

  - name: PIP | Install MySQL bridge
    pip: name={{ item }} state=present
    with_items:
    - MySQL-python